name: PR Build

on:
  pull_request:
    paths-ignore:
      - '**.md'

env:
  gradleFlags: --parallel --stacktrace --no-configuration-cache --no-daemon
  TG_CHAT: ${{ secrets.TG_CHAT }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  OAUTH_REDIRECT_URI: ${{ secrets.OAUTH_REDIRECT_URI }}
  OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}

jobs:
  build-and-telegram-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        shell: bash
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :presentation:reportForRelease $gradleFlags
      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: todolist-release-unspecified.apk
          path: presentation/build/outputs/apk/paid/release/todolist-release-unspecified.apk